-- Tabela única para a hierarquia Produto -> ProdutoFisico / ProdutoDigital
-- (estratégia SINGLE_TABLE; a coluna "tipo" é o discriminador).
CREATE TABLE produto (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo                VARCHAR(10)     NOT NULL,
    nome                VARCHAR(120)    NOT NULL,
    preco               NUMERIC(12, 2)  NOT NULL,
    peso_kg             DOUBLE PRECISION,
    dimensoes_cm        DOUBLE PRECISION,
    tamanho_arquivo_mb  DOUBLE PRECISION,
    criado_em           TIMESTAMP       NOT NULL,
    atualizado_em       TIMESTAMP       NOT NULL,

    CONSTRAINT ck_produto_tipo  CHECK (tipo IN ('FISICO', 'DIGITAL')),
    CONSTRAINT ck_produto_preco CHECK (preco >= 0)
);

CREATE INDEX idx_produto_nome ON produto (nome);
CREATE INDEX idx_produto_tipo ON produto (tipo);
